[package]
name = "tamari-cli"
version = "0.1.0"
authors = ["samsindt <samsground@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
url = "2.1.1"

[lib]
name = "tamari"
path = "src/lib.rs"